apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
        - name: node-js-container
          image: saimaali079/node.js:v1
          ports:
            - containerPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: node-js-service
spec:
  selector:
    app: node-js
  type: LoadBalancer
  ports:
    - port: 3003
      targetPort: 3003
